sudo: false
language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

os:
  - linux
  - osx
  - windows

cache:
  directories:
    - $HOME/.cargo

branches:
  only:
    - master
    
env:
 global:
   - RUST_BACKTRACE=1

before_script:
  - rustup component add clippy-preview
  - rustup component add rustfmt

script: 
  # Have rustfmt exit with error code if input is not formatted correctly.
  - cargo fmt --all -- --check
  - cargo build --verbose
  - cargo doc --verbose
  - cargo test --locked --verbose
  - cargo clippy --all-targets --all-features #  -D warnings
