max_width = 120
comment_width = 100
match_block_trailing_comma = true
wrap_comments = true
tab_spaces = 4
reorder_imports = true
reorder_modules = true
use_try_shorthand = true
error_on_line_overflow = true
