//! Errors generated by hexgrid library.

use derive_more::From;
use failure::Fail;

/// Errors thrown by Hexgrid.
#[derive(Debug, Fail, From)]
pub enum HexError {
    /// Unknown error.
    #[fail(display = "Unknown error")]
    UnknownError,
}
